# version: '3.8'

# services:
#   web:
#     build: .
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#   db:
#      image: postgres
#      volumes:
#         - postgres_data:/var/lib/postgresql/data/
#      ports:                       #add line.
#        - '5432'
#      environment:           # add line.
#        - POSTGRES_DB=postgres
#        - POSTGRES_USER=postgres
#        - POSTGRES_PASSWORD=postgres
# volumes:
#   postgres_data:  

version: '3.8'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000 
    environment:
      - ENVIRONMENT=development
      - NEW_SECRET_KEY=h91r*q+eya-i!qf-y1#pkp(3av$bjr((zqx&!_s_63%qpp(*)x
      - DEBUG=1
      # - STRIPE_TEST_PUBLISHABLE_KEY=<pk_test_your_publishable_key_here>
      # - STRIPE_TEST_SECRET_KEY=<sk_test_your_secret_key_here>
      - STRIPE_LIVE_PUBLISHABLE_KEY=<pk_live_your_publishable_key_here>
      - STRIPE_LIVE_SECRET_KEY=<sk_live_your_secret_key_here>
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    ports:                       #add line.
       - '5432'
    environment:           # add line.
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
